{{- range .Values.applications }}
{{- if ne .enabled false }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-{{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | quote }}
spec:
  project: {{ .project | quote }}
  source:
    repoURL: {{ $.Values.config.spec.source.repoURL | quote }}
    targetRevision: {{ $.Values.config.spec.source.targetRevision | quote }}
    path: {{ .path | quote }}
  destination:
    server: {{ $.Values.config.spec.destination.server | quote }}
    namespace: {{ .destination.namespace | quote }}
  syncPolicy: {}
  syncOptions:
    - CreateNamespace=true
{{- end }}
{{- end }}