apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workshop
  namespace: argocd
spec:
  description: Instructor-owned OKE workshop

  sourceRepos:
    - {{ .Values.config.spec.source.repoURL | quote }}
    - "https://oracle.github.io/karpenter-provider-oci/charts"
    - "https://kubernetes-sigs.github.io/metrics-server/"

  destinations:
    - server: {{ .Values.config.spec.destination.server | quote }}
      namespace: workshop-kpo

    - server: {{ .Values.config.spec.destination.server | quote }}
      namespace: karpenter-system

    - server: {{ .Values.config.spec.destination.server | quote }}
      namespace: kube-system

    - server: {{ .Values.config.spec.destination.server | quote }}
      namespace: kube-node-lease

    - server: {{ .Values.config.spec.destination.server | quote }}
      namespace: envoy-gateway-system

{{- range .Values.applications }}
{{- if ne .enabled false }}
    - server: {{ $.Values.config.spec.destination.server | quote }}
      namespace: {{ .destination.namespace | quote }}
{{- end }}
{{- end }}

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition

    - group: apiregistration.k8s.io
      kind: APIService

    - group: rbac.authorization.k8s.io
      kind: ClusterRole

    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

    - group: karpenter.sh
      kind: NodePool

    - group: karpenter.sh
      kind: NodeClaim

    - group: karpenter.sh
      kind: NodeOverlay

    - group: autoscaling.x-k8s.io
      kind: CapacityBuffer

    - group: oci.oraclecloud.com
      kind: OCINodeClass

    - group: gateway.networking.k8s.io
      kind: GatewayClass

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap

    - group: ""
      kind: LimitRange

    - group: ""
      kind: Pod

    - group: ""
      kind: ResourceQuota

    - group: ""
      kind: Secret

    - group: ""
      kind: Service

    - group: ""
      kind: ServiceAccount

    - group: apps
      kind: Deployment

    - group: apps
      kind: DaemonSet

    - group: apps
      kind: StatefulSet

    - group: policy
      kind: PodDisruptionBudget

    - group: networking.k8s.io
      kind: NetworkPolicy

    - group: rbac.authorization.k8s.io
      kind: Role

    - group: rbac.authorization.k8s.io
      kind: RoleBinding

    - group: autoscaling
      kind: HorizontalPodAutoscaler

    - group: gateway.networking.k8s.io
      kind: Gateway

    - group: gateway.networking.k8s.io
      kind: HTTPRoute

    - group: gateway.networking.k8s.io
      kind: ReferenceGrant

    - group: gateway.envoyproxy.io
      kind: EnvoyProxy