namespace: workshop-hpa

replicaCount: 1

image:
  repository: registry.k8s.io/hpa-example
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 50