apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.nodePool.name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    metadata:
      labels:
{{ toYaml .Values.nodePool.labels | nindent 8 }}
    spec:
      expireAfter: {{ .Values.nodePool.expireAfter | quote }}

      nodeClassRef:
        group: oci.oraclecloud.com
        kind: OCINodeClass
        name: {{ .Values.nodePool.nodeClassName | quote }}

      requirements:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux

        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64

        - key: karpenter.sh/capacity-type
          operator: In
          values:
{{ toYaml .Values.nodePool.capacityTypes | nindent 12 }}

        - key: oci.oraclecloud.com/instance-shape
          operator: In
          values:
{{ toYaml .Values.nodePool.shapes | nindent 12 }}

      taints:
{{ toYaml .Values.nodePool.taints | nindent 8 }}

      terminationGracePeriod: {{ .Values.nodePool.terminationGracePeriod | quote }}

  disruption:
    budgets:
      - nodes: 10%

    consolidateAfter: {{ .Values.nodePool.disruption.consolidateAfter | quote }}
    consolidationPolicy: {{ .Values.nodePool.disruption.consolidationPolicy | quote }}

  limits:
{{ toYaml .Values.nodePool.limits | nindent 4 }}