apiVersion: oci.oraclecloud.com/v1beta1
kind: OCINodeClass
metadata:
  name: {{ .Values.nodePool.nodeClassName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
{{- with .Values.oci.nodeCompartmentId }}
  nodeCompartmentId: {{ . | quote }}
{{- end }}
  shapeConfigs:
{{ toYaml .Values.nodePool.shapeConfigs | nindent 4 }}
  volumeConfig:
    bootVolumeConfig:
      imageConfig:
        imageType: OKEImage
{{- if .Values.oci.imageId }}
        imageId: {{ .Values.oci.imageId | quote }}
{{- else }}
        imageFilter:
{{ toYaml .Values.oci.imageFilter | nindent 10 }}
{{- end }}
  networkConfig:
    primaryVnicConfig:
      subnetConfig:
        subnetId: {{ required "charts/kpo: oci.workerSubnetId must be set" .Values.oci.workerSubnetId | quote }}
{{- with .Values.oci.primaryNetworkSecurityGroupIds }}
      networkSecurityGroupConfigs:
{{- range . }}
        - networkSecurityGroupId: {{ . | quote }}
{{- end }}
{{- end }}
{{- with .Values.oci.secondaryVnicConfigs }}
    secondaryVnicConfigs:
{{- range $index, $vnic := . }}
      - subnetConfig:
          subnetId: {{ required (printf "charts/kpo: oci.secondaryVnicConfigs[%d].subnetId must be set" $index) $vnic.subnetId | quote }}
{{- with $vnic.networkSecurityGroupIds }}
        networkSecurityGroupConfigs:
{{- range . }}
          - networkSecurityGroupId: {{ . | quote }}
{{- end }}
{{- end }}
        ipCount: {{ required (printf "charts/kpo: oci.secondaryVnicConfigs[%d].ipCount must be set" $index) $vnic.ipCount }}
{{- with $vnic.applicationResource }}
        applicationResource: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}