config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/ronsevetoci/workshop
      targetRevision: main

applications:
  - name: governance
    project: workshop
    path: charts/governance
    destination:
      namespace: workshop-governance
    syncWave: "10"

  - name: hpa
    enabled: false
    project: workshop
    path: charts/hpa
    destination:
      namespace: workshop-hpa
    syncWave: "20"

  - name: ingress
    enabled: false
    project: workshop
    path: charts/ingress
    destination:
      namespace: workshop-ingress
    syncWave: "30"

  - name: kpo
    enabled: true
    project: workshop
    destination:
      namespace: karpenter-system
    syncWave: "40"
    sources:
      - repoURL: https://oracle.github.io/karpenter-provider-oci/charts
        chart: karpenter
        targetRevision: "1.4.0"
        helm:
          releaseName: karpenter
          valuesObject:
            replicaCount: 1
            nodeSelector:
              kubernetes.io/os: linux
              oke.oraclecloud.com/pool.name: np-system
            tolerations:
              - key: CriticalAddonsOnly
                operator: Equal
                value: "true"
                effect: NoSchedule
            topologySpreadConstraints: []
            settings:
              clusterCompartmentId: "ocid1.compartment.oc1..aaaaaaaayevnkjfyjb6nglndfrvgoy7hciclgf4kq7ioulokey7xfpixjhxa"
              vcnCompartmentId: "ocid1.compartment.oc1..aaaaaaaayevnkjfyjb6nglndfrvgoy7hciclgf4kq7ioulokey7xfpixjhxa"
              apiserverEndpoint: "10.0.163.10"
              ociVcnIpNative: true
      - repoURL: https://github.com/ronsevetoci/workshop
        targetRevision: main
        path: charts/kpo