apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo
  namespace: {{ .Values.hpa.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app.kubernetes.io/name: hpa-demo
spec:
  replicas: {{ .Values.hpa.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: hpa-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hpa-demo
    spec:
      containers:
        - name: hpa-demo
          image: "{{ .Values.hpa.image.repository }}:{{ .Values.hpa.image.tag }}"
          imagePullPolicy: {{ .Values.hpa.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          resources:
{{ toYaml .Values.hpa.resources | nindent 12 }}