apiVersion: v1
kind: Service
metadata:
  name: hpa-demo
  namespace: {{ .Values.hpa.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  selector:
    app.kubernetes.io/name: hpa-demo
  ports:
    - name: http
      port: 80
      targetPort: http