apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kpo.workload.name | quote }}
  namespace: {{ .Values.kpo.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: {{ .Values.kpo.workload.name | quote }}

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP